### ISSUE TITLE
No module named py3compat

### ISSUE THREAD

**Issue by rashidsabbir** [tetherless-world/satoru#17]
Used the following trig files:
[examplePubInfo.trig.txt](https://github.com/tetherless-world/satoru/files/1468290/examplePubInfo.trig.txt)
[exampleProvenance.trig.txt](https://github.com/tetherless-world/satoru/files/1468291/exampleProvenance.trig.txt)
[exampleAssertion.trig.txt](https://github.com/tetherless-world/satoru/files/1468292/exampleAssertion.trig.txt)

**Comment by rashidsabbir** [comment]
Full error message:

Traceback (most recent call last):
  File "/apps/satoru/venv/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/apps/satoru/venv/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/apps/satoru/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/apps/satoru/venv/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/apps/satoru/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 270, in error_router
    return self.handle_error(e)
  File "/apps/satoru/venv/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/apps/satoru/venv/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/apps/satoru/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/apps/satoru/venv/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/apps/satoru/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 270, in error_router
    return self.handle_error(e)
  File "/apps/satoru/venv/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/apps/satoru/venv/lib/python2.7/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
    return view_func(**req.view_args)
  File "/apps/satoru/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/apps/satoru/venv/lib/python2.7/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/apps/satoru/venv/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/apps/satoru/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/apps/satoru/main.py", line 843, in post
    inputGraph = self._get_graph()
  File "/apps/satoru/main.py", line 815, in _get_graph
    sadi.deserialize(inputGraph, request.data, contentType)
  File "/apps/satoru/venv/lib/python2.7/site-packages/sadi/sadi.py", line 140, in deserialize
    f[1].deserialize(graph,content,mimetype)
  File "/apps/satoru/venv/lib/python2.7/site-packages/sadi/serializers.py", line 72, in deserialize
    graph.parse(data=content,format=self.inputFormat)
  File "/apps/satoru/venv/lib/python2.7/site-packages/rdflib/graph.py", line 1485, in parse
    context.parse(source, publicID=publicID, format=format, **args)
  File "/apps/satoru/venv/lib/python2.7/site-packages/rdflib/graph.py", line 1030, in parse
    parser = plugin.get(format, Parser)()
  File "/apps/satoru/venv/lib/python2.7/site-packages/rdflib/plugin.py", line 107, in get
    return p.getClass()
  File "/apps/satoru/venv/lib/python2.7/site-packages/rdflib/plugin.py", line 84, in getClass
    self._class = self.ep.load()
  File "/apps/satoru/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/apps/satoru/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/apps/satoru/venv/lib/python2.7/site-packages/rdflib_jsonld/parser.py", line 43, in <module>
    from .context import Context, Term, UNDEF
  File "/apps/satoru/venv/lib/python2.7/site-packages/rdflib_jsonld/context.py", line 14, in <module>
    from .util import source_to_json, urljoin, urlsplit, split_iri, norm_url
  File "/apps/satoru/venv/lib/python2.7/site-packages/rdflib_jsonld/util.py", line 7, in <module>
    from rdflib.py3compat import PY3, format_doctest_out
ImportError: No module named py3compat

**Comment by jimmccusker** [comment]
Hmm, yeah, it looks like rdflib-jsonld isn't ready for RDFlib 5.0 yet either.

**Comment by jimmccusker** [comment]
Updated rdflib-jsonld for RDFlib 5.
